# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './qt_view/new_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 541)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setTabsClosable(True)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = WidTabTemario(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tab_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCalenzadizador = QtWidgets.QMenu(self.menubar)
        self.menuCalenzadizador.setObjectName("menuCalenzadizador")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionCerrar = QtWidgets.QAction(MainWindow)
        self.actionCerrar.setObjectName("actionCerrar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionCalendarizar = QtWidgets.QAction(MainWindow)
        self.actionCalendarizar.setObjectName("actionCalendarizar")
        self.actionAgregar_calendario_comming = QtWidgets.QAction(MainWindow)
        self.actionAgregar_calendario_comming.setObjectName("actionAgregar_calendario_comming")
        self.actionCalendarizar_todo = QtWidgets.QAction(MainWindow)
        self.actionCalendarizar_todo.setObjectName("actionCalendarizar_todo")
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_como = QtWidgets.QAction(MainWindow)
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.menuFile.addAction(self.actionNuevo)
        self.menuFile.addAction(self.actionAbrir)
        self.menuFile.addAction(self.actionGuardar)
        self.menuFile.addAction(self.actionGuardar_como)
        self.menuFile.addAction(self.actionCerrar)
        self.menuFile.addAction(self.actionSalir)
        self.menuCalenzadizador.addAction(self.actionCalendarizar)
        self.menuCalenzadizador.addAction(self.actionCalendarizar_todo)
        self.menuCalenzadizador.addAction(self.actionAgregar_calendario_comming)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalenzadizador.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calendarizador UI"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("MainWindow", "Tab1"))
        self.menuFile.setTitle(_translate("MainWindow", "Archivo"))
        self.menuCalenzadizador.setTitle(_translate("MainWindow", "Calenzadizador"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.actionCerrar.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCalendarizar.setText(_translate("MainWindow", "Calendarizar"))
        self.actionAgregar_calendario_comming.setText(_translate("MainWindow", "Agregar calendario (comming)"))
        self.actionCalendarizar_todo.setText(_translate("MainWindow", "Calendarizar todo"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionNuevo.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionGuardar_como.setText(_translate("MainWindow", "Guardar como"))
        self.actionGuardar_como.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
from views.widgets.WidTabTemario import WidTabTemario
